FROM node:alpine AS build

WORKDIR /webshop/

COPY ./package*.json ./
COPY ./packages/frontend/package*.json ./packages/frontend/

RUN npm ci -w packages\/\frontend

COPY ./packages/frontend/ ./packages/frontend/

ARG WEBSHOP_API_URL
ENV APP_WEBSHOP_API_URL={WEBSHOP_API_URL}

RUN npm run build -w packages\/\frontend

FROM nginx:alpine
COPY --from=build /webshop/packages/frontend/dist/webstore /usr/share/nginx/html


