version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/myproducts

  frontend:
    build:
      dockerfile: Dockerfile.frontend
      args:
        WEBSHOP_API_URL: http://localhost:3000
    ports:
      - "4200:4200"

  mongoimport:
    image: library/mongo:latest
    container_name: webshop-data-import
    volumes:
      - .\packages\backend\src\data\products.json:/data/mongodb
    command: mongoimport --host mongodb --db myproducts --collection products --type json --file /data/mongodb --jsonArray

  mongodb:
    image: library/mongo:latest
    container_name: myproducts
    ports:
      - 27017:27017
    depends_on:
      - mongoimport
    restart: always
