FROM node:alpine

WORKDIR /webshop/src/app

COPY ./package*.json ./
COPY ./packages/frontend/package*.json ./packages/frontend/

RUN npm ci -w packages\/\frontend

COPY ./packages/frontend/ ./packages/frontend/

RUN npm run build -w packages\/\frontend

EXPOSE 3000

CMD [ "npx", "serve", "frontend/dist" ]


