FROM node:16-alpine

WORKDIR /webshop/

COPY ./package*.json ./
COPY ./packages/backend/package*.json ./packages/backend/

RUN npm ci -w packages\/\backend

COPY ./packages/backend/ ./packages/backend

RUN npm run build -w packages/\/backend

EXPOSE 3000

CMD ["node", "packages/backend/dist/main.js"]